### PR TITLE
feat: add favicon

### LINKED ISSUE #149: [Feat]: add favicon
### Feature request

add a favicon

### PR DESCRIPTION
**Pull request by Anuran12**
Closes #149

### CODE REVIEW

**Comment by Anuran12** [comment]
@schmelto  please check this

**Review by schmelto — CHANGES_REQUESTED** [review]
Maybe adding the Favicon in a separate folder would be great

**Comment by Anuran12** [comment]
@schmelto Done

**Review by schmelto — APPROVED** [review]
## Looking good to me

Your suggested changes looking good to me.

---
**Summary:** :ok_hand: This code looks good

**Pull request merged**
